name: Checks

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        paths:
            - '**.mts'
            - '**.json'
            - '**.yml'
            - '**.js'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 20
                    - 19
                    - 18
                    - 17
                    - 16
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        steps:
            - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
            - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
            - run: npm ci
            - run: npm run test:build
            - run: npm test -- --passWithNoTests
