name: Static Analysis (Linting...)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        paths:
            - '**.ts'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
            - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
              with:
                  node-version: 16.x
                  cache: npm
            - run: npm ci
            - run: npm run lint

    test:
        name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 16
                    - 14
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
            - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
            - run: npm ci
            - run: npm test -- --passWithNoTests
